# Generated by Django 2.1.7 on 2019-03-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_usergroup_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.CharField(choices=[('0', 'avatar0.png'), ('1', 'avatar1.png'), ('2', 'avatar2.png'), ('3', 'avatar3.png'), ('4', 'avatar4.png'), ('5', 'avatar5.png')], default='0', max_length=10),
        ),
    ]
