# Generated by Django 2.1.7 on 2019-03-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_auto_20190301_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.CharField(choices=[('avatar0.png', 'avatar0'), ('avatar1.png', 'avatar1'), ('avatar2.png', 'avatar2'), ('avatar3.png', 'avatar3'), ('avatar4.png', 'avatar4'), ('avatar5.png', 'avatar5')], default='0', max_length=10),
        ),
    ]
