# Generated by Django 2.1.7 on 2019-02-22 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_name', models.CharField(max_length=100)),
                ('bar_logo', models.ImageField(default='bar.png', upload_to='bar_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_prize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.TextField(blank=True, max_length=500, null=True)),
                ('group_logo', models.ImageField(default='group.png', upload_to='group_logos/')),
                ('members', models.ManyToManyField(related_name='member_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(null=True)),
                ('total_prize', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('order_state', models.BooleanField(default=False)),
                ('bar_combo', models.ManyToManyField(related_name='order_combo', to='order_app.Combo')),
                ('order_bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_bar', to='order_app.Bar')),
                ('order_members', models.ManyToManyField(related_name='order_member_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(blank=True, max_length=500, null=True)),
                ('product_logo', models.ImageField(default='product.png', upload_to='product_logos/')),
                ('bar_product', models.ManyToManyField(related_name='product_bar', to='order_app.Bar')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bar_prize', models.IntegerField(default=0)),
                ('product_bar_stock', models.BooleanField(default=False)),
                ('product_combo', models.ManyToManyField(related_name='product_combo', to='order_app.Combo')),
                ('product_order_list', models.ManyToManyField(related_name='product_order_list', to='order_app.OrderList')),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='bar_combo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bar_combo', to='order_app.Combo'),
        ),
    ]
