# Generated by Django 2.1.7 on 2019-02-22 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20190222_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variation_name', models.CharField(max_length=100)),
                ('product_variation_description', models.TextField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variation', to='order_app.Product')),
            ],
        ),
    ]
