# Generated by Django 2.1.7 on 2019-04-28 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_name', models.CharField(max_length=100)),
                ('bar_description', models.TextField(blank=True, max_length=500, null=True)),
                ('bar_color', models.CharField(default='yellow', max_length=100)),
                ('bar_official', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='group', to='account_app.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_prize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_combo', models.ManyToManyField(related_name='orderCombo', to='coffeeorder_app.Combo')),
                ('order_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderUserGroup', to='account_app.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True)),
                ('expiration', models.DateTimeField(blank=True)),
                ('total_prize', models.IntegerField(default=0)),
                ('order_bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Bar', to='coffeeorder_app.Bar')),
                ('order_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserGroup', to='account_app.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('product_color', models.CharField(default='white', max_length=100)),
                ('product_type', models.CharField(choices=[('COMIDA', 'comida'), ('BEBIDA', 'bebida')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bar_prize', models.IntegerField()),
                ('product_bar_stock', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffeeorder_app.Product')),
                ('product_bar_bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffeeorder_app.Bar')),
                ('product_bar_combo', models.ManyToManyField(related_name='Combo', to='coffeeorder_app.Combo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variation_name', models.CharField(default='NONE', max_length=300)),
                ('product_variation_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variation_product', to='coffeeorder_app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_order_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OrderList', to='coffeeorder_app.OrderList'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_product_bar',
            field=models.ManyToManyField(related_name='ProductBar', to='coffeeorder_app.ProductBar'),
        ),
    ]
