# Generated by Django 2.1.7 on 2019-03-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='bar_color',
            field=models.CharField(default='yellow', max_length=100),
        ),
        migrations.AddField(
            model_name='bar',
            name='bar_official',
            field=models.BooleanField(default=False),
        ),
    ]
