# Generated by Django 2.1.7 on 2019-03-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='expiration',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
