# Generated by Django 2.1.7 on 2019-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('FOOD', 'food'), ('DRINK', 'drink')], max_length=50),
        ),
    ]
