# Generated by Django 2.1.7 on 2019-04-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='groups',
            new_name='group',
        ),
    ]
