# Generated by Django 2.1.7 on 2019-05-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0002_auto_20190514_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='bar_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('0', 'food'), ('1', 'drink')], max_length=50),
        ),
    ]
