# Generated by Django 2.1.7 on 2019-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0003_auto_20190519_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_group',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(default='yellow', max_length=100),
        ),
    ]
