# Generated by Django 2.1.7 on 2019-05-20 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0004_auto_20190520_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('prize', models.FloatField(default=0)),
                ('order_product_bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OrderProductBar', to='coffeeorder_app.ProductBar')),
            ],
        ),
    ]
