# Generated by Django 2.1.7 on 2019-05-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0005_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductOrder', to='coffeeorder_app.Order'),
            preserve_default=False,
        ),
    ]
