# Generated by Django 2.1.7 on 2019-05-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0006_orderproduct_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='OrderItem',
        ),
    ]
