# Generated by Django 2.1.7 on 2019-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0008_remove_orderitem_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_product_bar',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
