# Generated by Django 2.1.7 on 2019-05-23 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffeeorder_app', '0009_auto_20190523_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='user_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orderListCreator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
