# Generated by Django 2.1.7 on 2019-05-23 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0010_orderlist_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_order_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderList', to='coffeeorder_app.OrderList'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_product_bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderProductBar', to='coffeeorder_app.ProductBar'),
        ),
    ]
