# Generated by Django 2.1.7 on 2019-06-03 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0011_auto_20190524_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bar', to='coffeeorder_app.Bar'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserGroup', to='account_app.UserGroup'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderListCreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
