# Generated by Django 2.1.7 on 2019-03-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group_color',
            field=models.CharField(default='white', max_length=100, unique=True),
        ),
    ]
