# Generated by Django 2.1.7 on 2019-03-13 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffeeorder_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group_bar',
            field=models.ManyToManyField(related_name='group_bar', to='coffeeorder_app.Bar'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group_members',
            field=models.ManyToManyField(related_name='groupMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
