# Generated by Django 2.1.7 on 2019-02-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_pic',
            field=models.ImageField(default='group_pics/coffee.png', upload_to='group_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/avatar.png', upload_to='profile_pics/'),
        ),
    ]
