# Generated by Django 2.1.7 on 2019-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeorder_app', '0001_initial'),
        ('account_app', '0003_auto_20190310_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group_bar',
            field=models.ManyToManyField(related_name='group_bar', to='coffeeorder_app.Bar'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_order_list',
            field=models.ManyToManyField(related_name='OrderList', to='coffeeorder_app.OrderList'),
        ),
    ]
