# Generated by Django 2.1.7 on 2019-03-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_usergroup_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
